name: Repo Sync

on:
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - run: |
        mkdir -p ../tmp
        cd ../tmp
        git clone https://github.com/nextcloud/all-in-one.git --depth 1 .
        cd ../all-in-one
        rm -rf ./*
        mv ../tmp/* ./
    - name: Commit files
      run: |
        git config --local user.email "workflow@github.com"
        git config --local user.name "GitHub Workflow"
        git add -A
        git commit -m "Repo-sync" || echo "Nothing to update"
    - name: Push changes
      uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
