name: Shellcheck

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  shellcheck:
    name: Check Shell
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
      with:
        check_together: 'yes'
      env:
        SHELLCHECK_OPTS: --shell bash
